# Generated by Django 2.2.4 on 2019-08-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='txn_flow',
            fields=[
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Verification Failed', 'Verification Failed'), ('Verified', 'Verified'), ('Rejected_by_blockchain', 'Rejected_by_blockchain'), ('Approved', 'Approved')], max_length=100)),
                ('txn_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
