# Generated by Django 2.2.4 on 2019-08-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='txn_flow',
            name='remarks',
            field=models.CharField(default='', max_length=200),
        ),
    ]
