# Generated by Django 2.2.4 on 2019-09-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_txn_flow_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='txn_flow',
            name='digitalID',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
