# Generated by Django 2.2.4 on 2019-09-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_auto_20190903_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='txn_flow',
            name='digital_id',
            field=models.CharField(max_length=20),
        ),
    ]
